name: FirstWorkflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Compile
        run: echo "Compile"
      - name: Run tests
        run: |
            echo "tests started"
            echo "tests successful"
